### ISSUE TITLE
Building not showing

### ISSUE THREAD

**Issue by Binnette** [OsmAnd-Rendering/Hiking#2]
Hi. TY for this excellent hiking rendering 👌

Sadly there is a bug, buildings are not showing. Buildings are so important when doing map. If you are a bit lost you can immediately find your location by looking the few buildings around you.

Did you do it on purpose? If so you should add a "how to add buildings" in your FAQ. Have a nice day 😇👍

OsmAnd 4.1.11 F-droid. Hiking profile downloaded just now

**Comment by Louis-LJ** [comment]
Hello!
the buildings are in the rendering. they are hidden in the "hide" setting
