### ISSUE TITLE
highway=track disappears when showing Details "Road State"

### ISSUE THREAD

**Issue by Binnette** [OsmAnd-Rendering/Hiking#3]
Initial rendering with default settings:
![image](https://user-images.githubusercontent.com/6597721/182369766-1feb57ba-fae2-4439-9d59-99c04114c1a5.png)

1. Open settings
2. Scroll down to "Details"
3. Enable "Road state" (Etat de la route)
  ![image](https://user-images.githubusercontent.com/6597721/182370039-2397678b-59b2-4f1c-87de-e521f6e81c3d.png)
5. Track disappears 😭 :
![image](https://user-images.githubusercontent.com/6597721/182370318-4607f922-9ab5-403b-9166-18b7fec4919d.png)

Thank you for fixing this bug. Have a nice day 😊

**Comment by Louis-LJ** [comment]
it's corrected  ; )

**Comment by Binnette** [comment]
Excellent. Thanks a lot ❤👍👍👍
