### ISSUE TITLE
natural=bare_rock are too "bold"/dark

### ISSUE THREAD

**Issue by Binnette** [OsmAnd-Rendering/Hiking#4]
Comparison between default OsmAnd foot rendering:
![image](https://user-images.githubusercontent.com/6597721/182373681-9f3177fa-1509-458f-81df-1ce052197238.png)

And the awesome Hiking rendering:
![image](https://user-images.githubusercontent.com/6597721/182373747-649e60bb-e4ad-46fe-99a0-861860442847.png)

1. The name "Col du Grand Van" is hardly readable in Hiking rendering https://www.osm.org/node/464779385
2. The contour lines (altitude lines) are difficult to read also

Example aera: https://www.openstreetmap.org/relation/11381611#map=14/45.0331/5.9243

**Comment by Louis-LJ** [comment]
it's corrected  ; )

**Comment by Binnette** [comment]
Tested, Approuved, Loved ❤
![Screenshot_20220802-200206_OsmAnd~](https://user-images.githubusercontent.com/6597721/182443085-ee8d7387-6153-4fc2-98ae-b350cd5f9015.jpg)
