### ISSUE TITLE
Default GPX color should not be purple

### ISSUE THREAD

**Issue by Binnette** [OsmAnd-Rendering/Hiking#6]
Hi the "rendering team" 😄 

I tested the awesome hiking profile this weekend. And I found one improvement that you can implement 👍 

In the profile, the default color when you record a GPX track is purple, but there is already a lot of purple on the map.
So maybe you can pick a different color 👍 

![2022-08-23 14_40_25](https://user-images.githubusercontent.com/6597721/186163151-7c9e63e9-c08a-4fc4-a6de-733b5e02fc7e.png)

TY and have a nice day 😄

**Comment by bobeeeze** [comment]
The colour of the gpx depends on the configuration of your profile and not on the rendering. At the beginning it asks you how you want to display it
![photo_2022-10-19_16-15-32](https://user-images.githubusercontent.com/59626956/196717095-efb182b7-cdc6-4484-acde-50f5beec3089.jpg)
