### ISSUE TITLE
a lot of walking trails were removed from the map

### ISSUE THREAD

**Issue by EugeneZmeuk** [OsmAnd-Rendering/Hiking#7]
https://www.reddit.com/r/OsmAnd/comments/xbx6s6/comment/io455nt/?utm_source=share&utm_medium=web2x&context=3

**Comment by Louis-LJ** [comment]
hello, 
I [replied](https://www.reddit.com/r/OsmAnd/comments/xbx6s6/comment/ipuocfa/?context=3) to the message and I did not find any problem detected at this place; )
